env:
  zilliqaNetwork: "https://api.zilliqa.com/"
  zilliqaApiWs: "wss://ws.zilliqa.com"
  nftMarketplaceAddress: "0x70b1f9e6a4d00baaf6972957f3b6a9f6c9f631b6"
  pg:
    host: postgres-zilkroad-mainnet
    database: postgres
    port: 5432
    user: postgres
    password: nPopdJL1bl

namespace: zilkroad-mainnet

image:
  app:
    pullSecret: aws-registry

replicas: 1
