env:
  zilliqaNetwork: "https://dev-api.zilliqa.com/"
  zilliqaApiWs: "wss://dev-ws.zilliqa.com"
  nftMarketplaceAddress: "0xad43392d1750771e58931801ddc274e5984660b4"
  pg:
    host: postgres-zilkroad.postgres.svc.cluster.local
    database: postgres
    port: 5432
    user: postgres
    password: TQN4EGYenx

namespace: zilkroad-testnet

image:
  app:
    pullSecret: aws-registry

# testnet instance covers staging
replicas: 0
