env:
  zilliqaNetwork: "https://dev-api.zilliqa.com/"
  zilliqaApiWs: "wss://dev-ws.zilliqa.com"
  nftMarketplaceAddress: "0xa4463b8d05eecd52249521e3d33447b0dceb17fb"
  pg:
    host: postgres-zilkroad.postgres.svc.cluster.local
    database: postgres
    port: 5432
    user: postgres
    password: TQN4EGYenx

namespace: zilkroad-testnet

image:
  app:
    pullSecret: aws-registry

replicas: 1
