env:
  zilliqaNetwork: "https://dev-api.zilliqa.com/"
  zilliqaApiWs: "wss://dev-ws.zilliqa.com"
  nftMarketplaceAddress: "0x8e7358f356fda73d450aed70dab7a93708b75650"
  pg:
    host: postgres-zilkroad.postgres.svc.cluster.local
    database: postgres
    port: 5432
    user: postgres
    password: eufdkov2BH

namespace: zilkroad-testnet

image:
  app:
    pullSecret: aws-registry

replicas: 1
