apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: chain-hook
  template:
    metadata:
      labels:
        service: chain-hook
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.app.pullSecret }}
      containers:
        - name: chain-hook
          image: "{{ .Values.image.app.url }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          ports:
          - containerPort: {{ .Values.port }}
          env:
            - name: ZILLIQA_NETWORK
              value: {{ .Values.env.zilliqaNetwork | quote }}
            - name: ZILLIQA_API_WS
              value: {{ .Values.env.zilliqaApiWs | quote }}
            - name: NFT_MARKETPLACE_ADDRESS
              value: {{ .Values.env.nftMarketplaceAddress | quote }}
            - name: PG_HOST
              value: {{ .Values.env.pg.host | quote }}
            - name: PG_DATABASE
              value: {{ .Values.env.pg.database | quote }}
            - name: PGPORT
              value: {{ .Values.env.pg.port | quote }}
            - name: PG_USER
              value: {{ .Values.env.pg.user | quote }}
            - name: PG_PASSWORD
              value: {{ .Values.env.pg.password | quote }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
