image:
  app:
    url: 981130112916.dkr.ecr.us-east-1.amazonaws.com/zilkroad/chain-hook
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: ~

port: 5000
targetPort: 5000
namespace: devnet

logPath: /app/logs

replicas:
  chainHook: 1

env:
  nftMarketplaceAddress: "0x0000000000000000000000000000000000000000"
  pgHost: "postgres"
  pgDatabase: "postgres"
  pgPort: 5432
  pgWriteUser: "postgres"
  pgWritePassword: "postgres_password"

resources:
  limits:
    cpu: 0.2
    memory: 128M
  requests:
    cpu: 0.2
    memory: 128M
